const GET_USER = "GET_USER";
const SET_USER = "SET_USER";
const IS_USER_LOADING = "IS_USER_LOADING";
const SET_USER_TOKEN = "SET_USER_TOKEN";
const SET_USER_TOKEN_IN_LOCAL_STORAGE = "SET_USER_TOKEN_IN_LOCAL_STORAGE";

export { IS_USER_LOADING, GET_USER, SET_USER, SET_USER_TOKEN, SET_USER_TOKEN_IN_LOCAL_STORAGE };
